### ISSUE TITLE
The post-formats tag should be removed, or the theme should support post formats

### ISSUE THREAD

**Issue by mirucon** [Olein-jp/oleinpress#2]
This theme has the post-formats tag in style.css, however it doesn't seem supporting post-formats.
You might want to support post formats, otherwise you should remove the tag.

```
add_theme_support( 'post-formats', array( 'audio', 'aside', 'chat', 'gallery', 'image', 'link', 'quote', 'status', 'video' ) );
```

**Comment by Olein-jp** [comment]
Thank you for posting the issue.

For now, I'd remove the post-format tag on style.css.
